### ISSUE TITLE
Classifier

### ISSUE THREAD

**Issue by mickahell** [mickahell/qhack21#20]
### Classification
_classifier.py : includes classifier circuit functions, e.g. datareupload(params), mykernelX(params), myqnn(params), etc._

- Receive the qubit from the device
- Create the circuit who classified the data 
ex :
<pre>
	   |------------|
	   | Classifier |
	   |----|--|----|
  |S(x)> --| RX |--| RZ |---
	   |----|--|----|
</pre>
- the output will be the state of the qubit (_1 or 0_)

**Comment by tvarga78** [comment]
For types of classifiers in general, see also this: https://github.com/mickahell/qhack21/issues/19#issuecomment-782733668

**Comment by mickahell** [comment]
I pushed a Simple one rotation classifier

**Comment by mickahell** [comment]
I pushed a Simple one rotation classifier circuit template
