### ISSUE TITLE
Graph

### ISSUE THREAD

**Issue by mickahell** [mickahell/qhack21#24]
### Graphing data
- Prepare graph to show the data input 
- Prepare the graph to show the data output
- Graph error

Link to #19 and #23

**Comment by mickahell** [comment]
Can be a good idea of representation to use _QuTiP_ and Matplotlib scatter points :
Ressource : https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/bloch-sphere-animation.ipynb

**Comment by tvarga78** [comment]
If we want to impress the jury with a concrete goal of the project, it can be this:

**Compare 2a with 2b (see above), that is, check if data re-uploading yields better classification.** (2b is the type of parameterized circuits that we saw many times during the challenge exercises, with no data re-uploading.)

**Comment by tvarga78** [comment]
A concrete goal of the project can be this:

**Compare 2a with 2b (see comment at "devices" issue), that is, check if data re-uploading yields better classification.** (2b is the type of parameterized circuits that we saw many times during the challenge exercises, with no data re-uploading.)
